name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: Print Github Parameter
        run: ${{ github }}
      - name: Print Inputs Parameter
        run: ${{ inputs }}
      - name: My not secret variable defined in github
        run: ${{ github.NOT_SECRET_VARIABLE }}