name: Test Using Self Hosted
run-name: Read Environment Variables
on:
  push:
    branches: [master]
  
# A workflow run is made up of one or more jobs that can run sequencially or in parallel
jobs:
  # This workflow contain a single job called build
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # step represent a sequence of tasks that will be executed as part of job
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so I can access it
      - name: Checkout Repo
        uses: actions/checkout@v3

  scalar:
    name: scalar_job
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Variable
        run: bash -e
      - name: Print Github Parameter
        run: ${{ github }}
      - name: Print Inputs Parameter
        run: ${{ inputs }}
      - name: My not secret variable defined in github
        run: ${{ github.NOT_SECRET_VARIABLE  
